dataloading:
  customized_focal: true
  customized_poses: false
  load_colmap_poses: true
  path: data/V_KITTI
  random_ref: 1
  resize_factor: 2
  scene:
  - intersection
  with_depth: true
depth:
  depth_loss_type: l1
  type: None
distortion:
  learn_distortion: true
  learn_shift: false
  learn_scale: false
extract_images:
  bspline_degree: 100
  eval_depth: true
  resolution:
  - 188
  - 621
  traj_option: interp
pose:
  init_R_only: false
  init_pose: true
  init_pose_type: colmap
  learn_R: true
  learn_focal: false
  learn_pose: true
  learn_t: true
  update_focal: true
training:
  auto_scheduler: true
  match_method: dense
  out_dir: out/V_KITTI/intersection_d9
  with_ssim: false
  t_cycle_weight: [1.0, 0.0]
